'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MiniDrawer from "./components/drawer";
// import { SnackbarProvider, useSnackbar } from "./snackbar-context";
// import CustomSnackbar from "./components/customSnackbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const { open, message, severity, closeSnackbar } = useSnackbar();


  return (
    <html lang="en">
      {/* <SnackbarProvider> */}
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <MiniDrawer>
            {children}
          </MiniDrawer>
          {/* <CustomSnackbar
                          message={message}
                          severity={severity}
                          open={open}
                          onClose={closeSnackbar}
                      /> */}
        </body>
      {/* </SnackbarProvider> */}
    </html>
  );
}
